name: exam_ready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Animations & UI
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Form Validation
  form_field_validator: ^1.1.0

  # Firebase (Latest stable versions as of Oct 2025)
  firebase_core: ^3.6.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.2

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Cloudinary Integration
  cloudinary_public: ^0.21.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.0.0

  # Networking & Media
  http: ^1.2.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  image: ^4.5.4
  url_launcher: ^6.2.4
  photo_view: ^0.15.0
  flutter_dotenv: ^6.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  
  # Riverpod State Management (Version 3.0 - All packages must match)
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  dio: ^5.9.0
  share_plus: ^12.0.0
  shimmer: ^3.0.0
  fake_cloud_firestore: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  
  # Riverpod Code Generation & Linting (Version 3.0 compatible)
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  build_runner: ^2.4.9
  custom_lint: 0.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - .env
