import 'package:exam_ready/screens/ui/entry_screen.dart';
import 'package:exam_ready/screens/ui/question_paper_submission_page.dart';
import 'package:exam_ready/screens/ui/search.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Exam Ready',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      home: const EntryScreen().animate().fadeIn(duration: 600.ms),
    );
  }
}
