// lib/config/firebase_config.dart
//
// DEPRECATED: This file is a duplicate of firebase_options.dart.
// The canonical Firebase configuration is generated by FlutterFire CLI
// and lives in lib/firebase_options.dart.
// This file re-exports for backward compatibility.

export '../firebase_options.dart';
